version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  web:
    build: .
    ports:
      - 9000:9000
    volumes:
      - .:/app
      - /app/vendor